### ISSUE TITLE
"Deployment" link to Digital Ocean.

### ISSUE THREAD

**Issue by Michelle4929** [phoenix-codecrafters/phoenix-codecrafters.github.io#3]
Issue-5. A section called “Deployment” containing a link to the deployed application running on Digital Ocean.

**Comment by stephanie-castelblanco** [comment]
http://104.131.171.137/ 


![Image](https://github.com/phoenix-codecrafters/phoenix-codecrafters.github.io/assets/156392785/f861ea09-e8dc-47af-a61a-0a81d4c6b2fb)



![Image](https://github.com/phoenix-codecrafters/phoenix-codecrafters.github.io/assets/156392785/62c446e2-77c3-4410-ba38-34bc06c1df0a)



![Image](https://github.com/phoenix-codecrafters/phoenix-codecrafters.github.io/assets/156392785/a6847043-7b37-4bb1-8ab6-f6342ab36fee)
